package auto

import (
	"time"

	"github.com/nitinda/microservice-change-log/api/models"
)

// changeLogs sample data
var changeLogs = []models.ChangeLog{
	models.ChangeLog{
		ServiceTeamName: "sales",
		ServiceName:     "hybris",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b5951ee6edddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "release",
		Username:        "user1",
		CreatedAt:       time.Date(2020, 11, 10, 10, 4, 58, 651387237, time.UTC),
	}, models.ChangeLog{
		ServiceTeamName: "sales",
		ServiceName:     "hybris",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b5951ee6eddff23asdfdc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "config",
		Username:        "user1",
		CreatedAt:       time.Date(2020, 11, 10, 10, 14, 58, 651387237, time.UTC),
	}, models.ChangeLog{
		ServiceTeamName: "sales",
		ServiceName:     "hybris",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b595asdf6eddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "release",
		Username:        "user22",
		CreatedAt:       time.Date(2020, 11, 10, 10, 24, 58, 651387237, time.UTC),
	}, models.ChangeLog{
		ServiceTeamName: "sales",
		ServiceName:     "hybris",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9bqwe51ee6eddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "config",
		Username:        "user3",
		CreatedAt:       time.Date(2020, 11, 10, 10, 34, 58, 651387237, time.UTC),
	}, models.ChangeLog{
		ServiceTeamName: "accommodation",
		ServiceName:     "accommData",
		Message:         "This is test config entry",
		EnvironmentName: "test",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02asdf9b5951ee6eddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "release",
		Username:        "user5",
	}, models.ChangeLog{
		ServiceTeamName: "accommodation",
		ServiceName:     "accommData",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b5951ee6eddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "config",
		Username:        "user1",
	}, models.ChangeLog{
		ServiceTeamName: "inventory",
		ServiceName:     "inventoryData",
		Message:         "This is test config entry",
		EnvironmentName: "test",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b5951ee6eddff23dc961basdf4bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "release",
		Username:        "user12",
	}, models.ChangeLog{
		ServiceTeamName: "inventory",
		ServiceName:     "inventoryData",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b5951ee6eddff23dc961basdf64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "config",
		Username:        "agent11",
	}, models.ChangeLog{
		ServiceTeamName: "inventory",
		ServiceName:     "inventoryData",
		Message:         "This is test config entry",
		EnvironmentName: "prod",
		ReleaseInfo:     "1.2.4",
		CommitHash:      "7b02a4c9b59dase6eddff23dc961b7d64bf32ebf",
		AgentInfo:       "jenkins",
		TypeOfChange:    "release",
		Username:        "agent1",
	},
}
